### ISSUE TITLE
Support EMR 6.5.0

### ISSUE THREAD

**Issue by ethnhll** [awslabs/amazon-emr-on-eks-custom-image-cli#12]
Currently when using emr-6.5.0 as a base for a custom image and then specifying this release label to the tool, there is a failure.

```
emr-on-eks-custom-image validate-image -i docker.io/library/emr6.5_custom -r emr-6.5.0
Amazon EMR on EKS - Custom Image CLI
Version: 1.01
... Checking if docker cli is installed
... Checking Image Manifest
[ERROR] No matching image with ReleaseName 'emr-6.5.0' : FAIL```

**Comment by ethnhll** [comment]
I am working on a fix for this, but it is not clear to me what logic was used to create the file list prefixes in the `image-manifest.yaml` file. 

At minimum, is it ok for me to remove the version numbers from the file dumps of these images and otherwise include a complete list of the files in 6.5?

**Comment by ethnhll** [comment]
@mkbarnum @zhuyulin27 @salilkansal 

Hey everyone, just want to send out a notification on this thread to get some eyes on it since it has been awhile without feedback.

I am not sure when EMR 6.6 will be out, but I'm guessing it's relatively soon. It would be awesome if we could keep the support of this tool up to date with the latest EMR releases

**Comment by zhuyulin27** [comment]
Hey Ethan,

Thanks for your feedback and sorry for the late reply! 
We plan to update the tool by April 13th for 6.5.0 and 5.34.0 releases. Once it's done, we will send a notice here as well.

We're not able to provide the `FilePrefix` list logic at this time. But if we have future plans, we will definitely update here. In case of delay in updates, we suggest to fork the tool and update it with your own business logic (Notes: Files in those 4 relative paths are important ones). This can also help you validate customized files and jars.

Hope this help resolve your question!
Best,

Yulin Zhu

**Comment by ethnhll** [comment]
Hi @zhuyulin27 thanks for getting back to me!

If you don't mind, I created a PR with the update to 6.5, and could use a review :)
https://github.com/awslabs/amazon-emr-on-eks-custom-image-cli/pull/13

**Comment by zhuyulin27** [comment]
Hey Ethan,

Yes I can help review the PR but will not merge it to the mainline.

**Comment by ethnhll** [comment]
>but will not merge it to the mainline

Are you not accepting PRs for this project then? I would not have spent any time trying to do this if public contributions are not accepted.

**Comment by zhuyulin27** [comment]
Hey Ethan,

We accept PRs for this project. My original thoughts is that we help update 6.5.0 and 5.34.0 with the artifacts by April 13th as you requested before. After looked at your PR, I think it's good to add missing files (if any) to the review and merge this PR when it's ready.

Sorry for the confusion. :)

**Comment by ethnhll** [comment]
Thanks for the clarification!

>After looked at your PR, I think it's good to add missing files (if any)

Thanks for taking a look, let me know if I missed anything, I'll be happy to update.

**Comment by zhuyulin27** [comment]
Hey Ethan, 

I reviewed the PR and sent 2 comments, could you please take a look?

Thanks!

**Comment by ethnhll** [comment]
Done, changes made to the manifest :)

**Comment by zhuyulin27** [comment]
Thanks Ethan, could you also rebase those commits into one with message "update support for 6.5.0 release"? Let's avoid redundant commits and keep commit history clean :)

**Comment by ethnhll** [comment]
Done

**Comment by zhuyulin27** [comment]
Changes merged, close the issue.
