### ISSUE TITLE
Support for EMR 6.6.0

### ISSUE THREAD

**Issue by grbinho** [awslabs/amazon-emr-on-eks-custom-image-cli#16]
According to this document
https://docs.aws.amazon.com/emr/latest/EMR-on-EKS-DevelopmentGuide/docker-custom-images-steps.html

EMR 6.6.0 latest should be supported, but when running the tool, I'm getting this error:

```
Amazon EMR on EKS - Custom Image CLI
Version: 1.02
... Checking if docker cli is installed
... Checking Image Manifest
[ERROR] No matching image with ReleaseName 'emr-6.6.0-latest' : FAIL
```

**Comment by zhuyulin27** [comment]
Hey Ivan,

According to the document: https://github.com/awslabs/amazon-emr-on-eks-custom-image-cli#support, emr-6.6.0 is currently not supported. We're working on updating emr-6.6.0 file structure and expecting the full update will be completed by 6/20/2022. Will comment here once the update is done.

Thanks

**Comment by grbinho** [comment]
Hi @zhuyulin27 

Thanks for the clarification and the timelines. 

I wrongly assumed that, given the AWS docs recommend doing this verification and are linking here, releases would be synchronized.

I see that EMR 6.6.0 was released about a month ago (9th of May), would 1 to 2 months delay be the usual timeline?

Thanks!

**Comment by zhuyulin27** [comment]
Hey Ivan, 

The version updates are not automatic yet and manual updates may take some time. Before we can automate this process, you can raise an issue to ask for an acceleration or send a PR to customize the tool.

Sorry for the inconvenience!

Thanks

**Comment by zhuyulin27** [comment]
Hey Ivan, emr-6.6.0 and emr-5.36.0 release are updated. Thanks!
