### ISSUE TITLE
Support for EMR 6.7.0

### ISSUE THREAD

**Issue by Swalloow** [awslabs/amazon-emr-on-eks-custom-image-cli#18]
Hi, EMR 6.7.0 latest should be supported.
https://docs.aws.amazon.com/emr/latest/EMR-on-EKS-DevelopmentGuide/emr-eks-6.7.0.html

**Comment by Swalloow** [comment]
Hi @zhuyulin27,
I created a PR to support 6.7.0 release. Could you help review the PR?
Thanks!

**Comment by timvw** [comment]
Any updates? What about later releases?
