### ISSUE TITLE
Support for EMR 6.10.0, 6.11.0

### ISSUE THREAD

**Issue by eightlimbed** [awslabs/amazon-emr-on-eks-custom-image-cli#23]
Hello, we would like to use this tool, but the last supported version is EMR 6.6.0. Can you please update it to support the EMR releases?

**Comment by zhuyulin27** [comment]
Closed as updated support to 6.13.0 in PR: https://github.com/awslabs/amazon-emr-on-eks-custom-image-cli/pull/25
