### ISSUE TITLE
release emr-6.4.0 is not supported

### ISSUE THREAD

**Issue by jaehyeon-kim** [awslabs/amazon-emr-on-eks-custom-image-cli#9]
Hi

Can you please include `emr-6.4.0 as well?

```
$ emr-on-eks-custom-image validate-image -i tmp:latest -r emr-6.4.0
Amazon EMR on EKS - Custom Image CLI
Version: 1.00
... Checking if docker cli is installed
... Checking Image Manifest
[ERROR] No matching image with ReleaseName 'emr-6.4.0' : FAIL
```

Cheers,
Jaehyeon

**Comment by zhuyulin27** [comment]
Thanks for the feedback. We're working on updating the tool with the latest release, expected date of completion 01/14. Once it's done, we will send a notice here as well. 
Let us know if you have more questions!

**Comment by zhuyulin27** [comment]
Hello Jaehyeon,

We have updated the tool to v1.01 which supports EMR 6.4.0 releases. You can either download the new releases or use Homebrew(recommended for Mac/Linux) to upgrade your tool.

Best,
Yulin

**Comment by jaehyeon-kim** [comment]
Thank you @zhuyulin27 !
